    <?php
	if($_SERVER['REMOTE_ADDR']=='80.56.110.88'){
    ?>
<div class="block block-usp">
<div class="block-title"><strong>Chat</strong></div>
<div class="block-content" style="text-align:center;">
<div id="ci3lc5" style="z-index:100;position:absolute"></div><div id="sc3lc5" style="display:inline"></div><div id="sd3lc5" style="display:none"></div><script type="text/javascript">var se3lc5=document.createElement("script");se3lc5.type="text/javascript";var se3lc5s=(location.protocol.indexOf("https")==0?"https":"http")+"://image.providesupport.com/js/hollandgold/safe-standard.js?ps_h=3lc5&ps_t="+new Date().getTime();setTimeout("se3lc5.src=se3lc5s;document.getElementById('sd3lc5').appendChild(se3lc5)",1)</script><noscript><div style="display:inline"><a href="http://www.providesupport.com?messenger=hollandgold">Customer Support Chat</a></div></noscript>
</div>
</div>
<?php
	};
	?>