<div class="col-xs-6 text-center">
<?php
$product = $this->getFeaturedProduct();
$productBlock = new Mage_Catalog_Block_Product;
$store = Mage::app()->getStore();
$code  = $store->getCode();
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($product);

if($stock->getQty() > 0) {
	echo '<div class="labeldirect"><img src="/skin/frontend/default/hollandgold/images/label_available.png" alt="'.$this->__('Direct beschikbaar').'" title="'.$this->__('Direct beschikbaar').'" /></div>';
}
?>
<a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getData('name'); ?>" class="product-image">
    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(150);?>" alt=="<?php echo $product->getData('name'); ?>">
</a><br>

<a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getData('name'); ?><br></a>
<?php echo $productBlock->getPriceHtml($product); ?>


<div class="actions">
    <?php if($product->isSaleable()): ?>
        
            <a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:setLocationAjax('<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>')
    				 <?php else: ?><?php echo $this->getAddToCartUrl($product); ?>
    				 <?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span><i class="icon-cart"></i></a>

            <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$product->getId()));?>' class='fancybox' id='fancybox<?php echo $product->getId()?>' style='display:none'>Options</a>
       
    <?php else: ?>
        <a href="javascript:void(0);" class="addtocart outofstock" title="<?php echo $this->__('Out of stock') ?>"><span><?php echo $this->__('Out of stock') ?></span></a>
    <?php endif; ?>
   
    <div class="clearer"></div>
</div>
</div>
<div class="col-xs-6">
    <h2>In de kijker</h2>
    <?php echo $product->getData('featured_product_short_descr'); ?>
</div>
<div class="clearer"></div>