<?php
/**
 Made by Smartwave.
 */
?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $footer = Mage::getStoreConfig('porto_settings/footer',$code);
?>
<div class="block block-subscribe">
    <div class="block-title">
        <h4><?php echo $footer['footer_newsletter_title']; ?></h4>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="footer-newsletter-validate-detail" onsubmit="setNewsletterCookie()">
        <div class="block-content">
            <p><?php echo $footer['footer_newsletter']; ?></p>
            <div class="input-box">
                <p class="label"><?php echo $this->__('Enter your e-mail Address'); ?></p>
                <input class="input-text required-entry validate-email" type="text" name="email" id="newsletter_footer" title="<?php echo $this->__('Sign up for our newsletter') ?>" />
                <button class="button" id="buttonSubmit" title="<?php echo $this->__('Submit') ?>"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                <div class="g-recaptcha" data-sitekey="6LdWuyIUAAAAAAGV_-f0b_uRaQ-byPvVNDCLrBWq" data-callback='submitForm1' data-size="invisible"></div>
                <div class="clearer"></div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var footernewsletterSubscriberFormDetail = new VarienForm('footer-newsletter-validate-detail');
    //]]>
    </script>

    <script type="text/javascript">
        function submitForm1(token) {

            document.getElementById("footer-newsletter-validate-detail").submit();
        }

        function validate(event){
            event.preventDefault();
            if(Validation.validate(document.getElementById('newsletter_footer'))){
                grecaptcha.execute();
            }
        }

        document.addEventListener('DOMContentLoaded', function() {
            const button = document.querySelector('#buttonSubmit');
            button.addEventListener('click', validate);
        });

    </script>

</div>
