<?php if ($posts = $this->getRecent()): ?>
<div class="block-news large">
<div class="block-title">
    <h3><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h3>
</div>
<div class="block-content">
    <ul>
    <?php foreach ($posts as $post): ?>
        <li class="row">
            <div class="post-content col-xs-12">
                <h3><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>
                <div class="post-time"><?php echo Mage::helper('core')->formatDate($post->getCreatedTime(), 'long', false); ?></div>
                <div class="post-excerpt">
                    <p><?php echo $post->getShortContent(); ?></p>
                    <a class="button btn-more" href="<?php echo $post->getAddress(); ?>"><?php echo Mage::helper('blog')->__('Read more'); ?></a>
                </div>
            </div>
            <div class="clear"></div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>    
</div>
<?php endif; ?>